    # NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

4.Scientific Computing & Simulations


In [1]:
import numpy as np

## 2. Importing NumPy

In [35]:
import numpy as np

## 3. Arrays vs Python Lists

In [34]:
import numpy as np
import time

py_list = [i for i in range(1000000)]


# NumPy array

In [ ]:
np_array = np.arange(1000000)

Python list sum time: 0.003889799118041992
NumPy array sum time: 0.0014348030090332031


# Time comparison

In [33]:
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)

Python list sum time: 0.03819608688354492
NumPy array sum time: 0.012313127517700195


## 4. Creating Arrays
1.np.arange(start, stop, step)

Purpose: Creates an array of numbers starting from start up to but not including stop, incremented by step.

Your code: np.arange(0, 10, 2)

Start = 0

Stop = 10 (exclusive)

Step = 2

2.np.linspace(start, stop, num)

Purpose: Creates an array of num equally spaced numbers between start and stop (inclusive).

Your code: np.linspace(0, 1, 5)

Start = 0

Stop = 1 (inclusive)

5 numbers evenly spaced

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# From list 


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


# Zeros and Ones


In [14]:
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]


# Range and Linspace

In [21]:
print("Arange:", np.arange(0, 100, 19))
print("Linspace:", np.linspace(0, 100, 6))

Arange: [ 0 19 38 57 76 95]
Linspace: [  0.  20.  40.  60.  80. 100.]


## 5. Array Properties

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

Array shape: (3, 3)
Array dtype: int64
Array size: 9
Array ndim: 2


In [31]:
## 6. Indexing and Slicing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [29]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int64
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]


In [32]:
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
## 7. Operations and Broadcasting
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


In [27]:
## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [28]:
## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
ar = np.arange(1, 10, 1)
ar = ar.reshape(3, 3)
print(ar[1])

[4 5 6]


4.Generate a random 5×5 matrix and find its maximum and minimum values.
 
(Hint: Use np.random.rand for random numbers)

In [51]:
arr = np.random.randint(0, 100, (5,5))
print("Random 5x5 Matrix:\n", arr)
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))

Random 5x5 Matrix:
 [[ 2 38 39 50 66]
 [61 36 65 16 79]
 [66 54 88 72  7]
 [99 87 89 38 54]
 [29 70 79 50 26]]
Maximum value: 99
Minimum value: 2
